### ISSUE TITLE
Add Netlify CMS for Spots

### ISSUE THREAD

**Issue by mirhamasala** [mirhamasala/mirhamasala.com#154]
```
If you're deploying with Vercel, you can still use Netlify CMS. The setup is slightly more complex since you'll be using a different deployment platform than the one Netlify CMS is originally tailored for. Here's a step-by-step guide on how to set up Netlify CMS with a Next.js app hosted on Vercel:

1. **Set Up Netlify CMS**:

   - Install the necessary dependencies:
     ```
     npm install --save netlify-cms-app
     ```

   - Create a static `admin` folder in your `public` directory with an `index.html` and a `config.yml`. The `index.html` is typically just the CMS entry point provided by Netlify CMS.

2. **Configure Netlify CMS**:

   In your `public/admin/config.yml`:

   ```yml
   backend:
     name: github
     repo: username/repo # path to your GitHub repository
     branch: main # branch to edit (optional)
     base_url: your-oauth-provider-server.com
     auth_endpoint: /auth

   media_folder: "public/images" 
   public_folder: "/images"

   collections:
     - name: "spots"
       label: "Spots"
       folder: "data/spots"
       create: true
       slug: "{{slug}}"
       fields:
         # ... (as previously defined)
   ```

3. **Set Up OAuth for GitHub**:

   Since you won't be deploying on Netlify, you'll need an external OAuth provider to authenticate with GitHub. One of the easiest ways to do this is to use Netlify's own [GoTrue](https://github.com/netlify/gotrue) or [netlify-cms-oauth-provider-node](https://github.com/vencax/netlify-cms-github-oauth-provider) or similar projects. These tools will provide the OAuth endpoint you need to authenticate from Vercel. 

   - Deploy one of these projects, grab the URL, and update the `base_url` in your `config.yml` accordingly.

4. **Fetching Data in Next.js**:

   The process is the same as previously described: Netlify CMS will save each spot as a markdown or JSON file in the specified directory (e.g., `data/spots`), and you'll use Next.js methods to fetch this data.

5. **Deploy on Vercel**:

   Since your content is now managed through Netlify CMS and stored in your GitHub repository, you can deploy your Next.js app on Vercel as you normally would. Changes made in the CMS will create commits in your repo, which can then trigger Vercel to redeploy your site.

Remember, you'll need to have the necessary environment variables set up on Vercel to allow for GitHub authentication (e.g., OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET from your GitHub OAuth app).

```
